### ISSUE TITLE
source regen timers are going to negative

### ISSUE THREAD

**Issue by thmsndk** [thmsndk/Screeps3D#42]
![image](https://user-images.githubusercontent.com/9084377/60217717-a21a4a80-986d-11e9-82c0-b0ac423a20cd.png)

**Comment by Robalian** [comment]
I'm pretty sure I fixed it for all kinds of regeneration panels... How did you get this?

**Comment by AlinaNova21** [comment]
This happens on official client too in some cases. Inactive rooms (rooms with no owned structures), only get updated periodically, so its possible to have negative regen times if you look at them.

**Comment by thmsndk** [comment]
I was just browsing around trying to find source node because of another feature I was working on and I stumpled upon it on official shard3, think it was this room
https://screeps.com/a/#!/room/shard3/E18S39

![image](https://user-images.githubusercontent.com/9084377/60219884-85354580-9874-11e9-9055-62688d1115f8.png)

So that would be in line with what ags131 mentioned above

**Comment by Robalian** [comment]
close?

**Comment by thmsndk** [comment]
It is still an issue, that it goes negative :) unless someone has handled that case ags131 mentioned and i've posted a screenshot of

**Comment by M1kep** [comment]
I believe the issue is the API is returning a negative value as the server has put the room in "eco" mode
